global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # เก็บ metrics ของ Node API (/metrics)
  - job_name: "api"
    metrics_path: /metrics
    static_configs:
      - targets: ["app:4000"]

  # เก็บ metrics ของ host ผ่าน node_exporter
  - job_name: "node"
    static_configs:
      - targets:
          - "98.89.193.1:9100"      # <-- นคอเครองปจจบน (Host)
          - "54.162.148.251:9100"
          - "34.229.0.66:9100"